#lambda functions

Resources:
  AuthTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Auth-${self:provider.stage}
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI_1_PK
          AttributeType: S
        - AttributeName: GSI_1_SK
          AttributeType: S
        - AttributeName: GSI_2_PK
          AttributeType: S
        - AttributeName: GSI_2_SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: InvertedIndex
          KeySchema:
            - AttributeName: SK
              KeyType: HASH
            - AttributeName: PK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI_1
          KeySchema:
            - AttributeName: GSI_1_PK
              KeyType: HASH
            - AttributeName: GSI_1_SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI_2
          KeySchema:
            - AttributeName: GSI_2_PK
              KeyType: HASH
            - AttributeName: GSI_2_SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
